### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by meredithcat** [will0101/Graph-Tutorial#2]
Challenge 1 Feedback: 6/20
Code based on Challenge 1 Rubric

Code looks good! Need to add tests, error handling, and processing of Digraph.

- Solution: 1 (x2 = 2)
  - Code only works on Graph, not Digraph.
  - If there is a new vertex in the edge inputs, KeyError is thrown without error message

- Documentation: 1
  - Include docstrings on all methods (parse_data, create_graph).

- Code organization: 3
  - Code is loosely coupled and all functions/classes have a purpose! :)
  - The '__str__' function has unintended side effect.

- Testing: 0
  - Add unit tests!

**Comment by will0101** [comment]
Update

**Comment by meredithcat** [comment]
Challenge 1 Feedback (Resubmit): 13/20

- Solution: 3 (x2 = 6)
  - Code works on Graph/Digraph and weighted/unweighted
  - Throws appropriate error messages

- Documentation: 2
  - Includes docstrings on almost all methods

- Code organization: 3
  - Code is loosely coupled and all functions/classes have a purpose! :)
  - The '__str__' function has unintended side effect.

- Testing: 2
  - No tests for parse_data, create_graph, print_graph
